    apiVersion: v1
    kind: Service
    metadata:
     name: web
     labels:
       layer: web
    spec:
#     type: LoadBalancer
     type: NodePort
     ports:
       - port: 80
         nodePort: 30080
#         hostPort: 
         targetPort: http-port
         protocol: TCP
     selector:
       layer: web
