    apiVersion: v1
    kind: Service
    metadata:
     name: web
     labels:
       layer: web
    spec:
#     type: LoadBalancer
#     type: ClusterIP
     type: NodePort
     ports:
       - port: 80
         targetPort: http-port
         protocol: TCP
     selector:
       layer: web
