    apiVersion: v1
    kind: Service
    metadata:
     labels:
       name: mongo
     name: mongo
    spec:
     ports:
         # Port forwarding from Service to Pod
       - port: 27017
         targetPort: 27017
     selector:
       name: mongo